--- 
apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-col-migrator
spec:
  parallelism: 1
  template:
    metadata:
      name: mongo-col-migrator
    spec:
      containers:
        - name: mongo-col-migrator
          image: lovellfelix/mongo-col-migrator:v1.2.1
          env:
          - name: MONGO_URI_SOURCE
            value: "mongodb+srv://user@pass:hostname/source?retryWrites=true&w=majority" 
          - name: MONGO_SOURCE_DATABASE
            value: source
          - name: MONGO_SOURCE_COLLECTION
            value: "collection_a"
          - name: MONGO_URI_DESTINATION
            value: "mongodb+srv://user@pass:hostname/destination?retryWrites=true&w=majority" 
          - name: MONGO_DESTINATION_DATABASE
            value: "destination"
          - name: MONGO_DESTINATION_COLLECTION
            value: "collection_b"
      restartPolicy: OnFailure